# Dockerfile creating a container for use with the TensorFlow Object Detection API 
# If you're running on a machine without GPU, change "tensorflow:1.9.0-gpu-py3" to "tensorflow:1.9.0-py3 "

FROM tensorflow/tensorflow:1.12.0-gpu-py3 

RUN mkdir /lib/tf
COPY set_up_object_detection_api.sh /lib/tf/set_up_object_detection_api.sh

RUN sh /lib/tf/set_up_object_detection_api.sh

ENV PYTHONPATH=$PYTHONPATH:/lib/tf/models/research:/lib/tf/models/research/slim

CMD ["echo", "Image created"] 
